### ISSUE TITLE
sync不成功

### ISSUE THREAD

**Issue by jiangshua** [luqinx/sp#1]
项目下载下来sync不成功，方便留个微信群吗？

**Comment by luqinx** [comment]
请同步一下最新的代码，并在项目根目录下执行如下命令 (windows系统可参考根目录下的 <项目第一次编译.md>)
ln -s `pwd`/autoservice/src/main/groovy/chao/android/gradle/servicepool/ buildSrc/src/main/groovy/chao/android/gradle/

**Comment by luqinx** [comment]
问题已修复， 
感兴趣可加个人微信:  704896571
